# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            EasyAdmin Blog
tagline:          ''
description:      '<a target="_blank" href="https://github.com/EasyCorp/EasyAdminBundle">EasyAdmin</a> is a popular admin generator for <a target="_blank" href="https://symfony.com">Symfony</a> applications.'
url:              https://easycorp.github.io/blog
baseurl:          https://easycorp.github.io/blog

author:
  name:           'Javier Eguiluz'
  email:           'javier.eguiluz@gmail.com'
  url:            https://github.com/javiereguiluz

paginate:         10

# Custom vars
github:
  repo:           https://github.com/EasyCorp/EasyAdminBundle
